[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
restartPolicyType = "always"

[nixpacks]
providers = ["python"]
pythonVersion = "3.11"

[variables]
# Railway will automatically set PORT environment variable
PORT = "8080"

[build.watchPatterns]
include = ["**/*.py", "requirements.txt", ".env.example", "config.py"]
exclude = ["__pycache__/**", "*.pyc", "logs/**", "data/**", "exports/**", "venv/**"]