[build]
builder = "nixpacks"
watchPatterns = ["**/*.py", "requirements.txt", "config.py", "bot/**", "main.py"]

[deploy]
startCommand = "python main.py"
restartPolicyType = "always"

[nixpacks]
providers = ["python"]
pythonVersion = "3.11"